package v1alpha3

import (
	"github.com/weaveworks/ignite/pkg/apis/ignite"
	"k8s.io/apimachinery/pkg/conversion"
)

// Convert_ignite_ConfigurationSpec_To_v1alpha3_ConfigurationSpec calls the autogenerated conversion function along with custom conversion logic
func Convert_ignite_ConfigurationSpec_To_v1alpha3_ConfigurationSpec(in *ignite.ConfigurationSpec, out *ConfigurationSpec, s conversion.Scope) error {
	return autoConvert_ignite_ConfigurationSpec_To_v1alpha3_ConfigurationSpec(in, out, s)
}
